module

public import Mathlib.Geometry.Manifold.IsManifold.Basic

@[expose] public section

/-!
# Manifold Adventure: browser theorem base

Generated by `scripts/create-manifold-game.mjs`.

Exercise declarations live in `ManifoldAdventure`; the mathematical
structures and library theorems they use come directly from pinned Mathlib.
-/

namespace ManifoldAdventure

universe u v w u' v'

open scoped Topology ContDiff
open Filter ENat

theorem homeomorph_continuous {X : Type u} {Y : Type v} [TopologicalSpace X] [TopologicalSpace Y]
    (e : X ≃ₜ Y) : Continuous e := by
  exact e.continuous

theorem homeomorph_inverse_continuous {X : Type u} {Y : Type v} [TopologicalSpace X] [TopologicalSpace Y]
    (e : X ≃ₜ Y) : Continuous e.symm := by
  exact e.continuous_symm

theorem homeomorph_round_trip {X : Type u} {Y : Type v} [TopologicalSpace X] [TopologicalSpace Y]
    (e : X ≃ₜ Y) (x : X) : e.symm (e x) = x := by
  exact e.symm_apply_apply x

theorem homeomorph_composition_apply {X : Type u} {Y : Type v} {Z : Type w}
    [TopologicalSpace X] [TopologicalSpace Y] [TopologicalSpace Z]
    (e : X ≃ₜ Y) (f : Y ≃ₜ Z) (x : X) : e.trans f x = f (e x) := by
  exact Homeomorph.trans_apply e f x

theorem local_chart_source_open {X : Type u} {Y : Type v} [TopologicalSpace X] [TopologicalSpace Y]
    (e : OpenPartialHomeomorph X Y) : IsOpen e.source := by
  exact e.open_source

theorem local_chart_continuous {X : Type u} {Y : Type v} [TopologicalSpace X] [TopologicalSpace Y]
    (e : OpenPartialHomeomorph X Y) : ContinuousOn e e.source := by
  exact e.continuousOn

theorem local_chart_maps_source {X : Type u} {Y : Type v} [TopologicalSpace X] [TopologicalSpace Y]
    (e : OpenPartialHomeomorph X Y) (x : X) (hx : x ∈ e.source) : e x ∈ e.target := by
  apply e.map_source
  exact hx

theorem local_chart_round_trip {X : Type u} {Y : Type v} [TopologicalSpace X] [TopologicalSpace Y]
    (e : OpenPartialHomeomorph X Y) (x : X) (hx : x ∈ e.source) : e.symm (e x) = x := by
  exact e.left_inv hx

theorem point_mem_preferred_chart {H : Type u} {M : Type v} [TopologicalSpace H] [TopologicalSpace M]
    [ChartedSpace H M] (x : M) : x ∈ (chartAt H x).source := by
  exact mem_chart_source H x

theorem preferred_chart_mem_atlas {H : Type u} {M : Type v} [TopologicalSpace H] [TopologicalSpace M]
    [ChartedSpace H M] (x : M) : chartAt H x ∈ atlas H M := by
  exact chart_mem_atlas H x

theorem preferred_chart_maps_to_target {H : Type u} {M : Type v} [TopologicalSpace H] [TopologicalSpace M]
    [ChartedSpace H M] (x : M) : chartAt H x x ∈ (chartAt H x).target := by
  exact mem_chart_target H x

theorem preferred_chart_source_is_neighborhood {H : Type u} {M : Type v} [TopologicalSpace H] [TopologicalSpace M]
    [ChartedSpace H M] (x : M) : (chartAt H x).source ∈ 𝓝 x := by
  exact chart_source_mem_nhds H x

theorem preferred_charts_cover {H : Type u} {M : Type v} [TopologicalSpace H] [TopologicalSpace M]
    [ChartedSpace H M] : (⋃ x : M, (chartAt H x).source) = (Set.univ : Set M) := by
  exact iUnion_source_chartAt H M

theorem self_chart_is_identity {H : Type u} [TopologicalSpace H] (x : H) :
    chartAt H x = OpenPartialHomeomorph.refl H := by
  exact chartAt_self_eq

theorem self_atlas_only_identity {H : Type u} [TopologicalSpace H] (e : OpenPartialHomeomorph H H) :
    e ∈ atlas H H ↔ e = OpenPartialHomeomorph.refl H := by
  constructor
  · intro h
    exact chartedSpaceSelf_atlas.mp h
  · intro h
    exact chartedSpaceSelf_atlas.mpr h

theorem product_chart_is_product {H : Type u} {H' : Type u'} {M : Type v} {M' : Type v'}
    [TopologicalSpace H] [TopologicalSpace H'] [TopologicalSpace M] [TopologicalSpace M']
    [ChartedSpace H M] [ChartedSpace H' M'] (x : M × M') :
    chartAt (ModelProd H H') x = (chartAt H x.1).prod (chartAt H' x.2) := by
  rw [prodChartedSpace_chartAt]

theorem product_point_mem_chart_source {H : Type u} {H' : Type u'} {M : Type v} {M' : Type v'}
    [TopologicalSpace H] [TopologicalSpace H'] [TopologicalSpace M] [TopologicalSpace M']
    [ChartedSpace H M] [ChartedSpace H' M'] (x : M) (y : M') :
    (x, y) ∈ (chartAt (ModelProd H H') (x, y)).source := by
  simpa only using (mem_chart_source (ModelProd H H') (x, y))

theorem model_space_is_manifold {𝕜 : Type u} [NontriviallyNormedField 𝕜]
    {E : Type v} [NormedAddCommGroup E] [NormedSpace 𝕜 E]
    {H : Type w} [TopologicalSpace H] (I : ModelWithCorners 𝕜 E H) (n : WithTop ℕ∞) :
    IsManifold I n H := by
  infer_instance

theorem manifold_of_higher_smoothness {𝕜 : Type u} [NontriviallyNormedField 𝕜]
    {E : Type v} [NormedAddCommGroup E] [NormedSpace 𝕜 E]
    {H : Type w} [TopologicalSpace H] {I : ModelWithCorners 𝕜 E H}
    {M : Type u'} [TopologicalSpace M] [ChartedSpace H M]
    {m n : WithTop ℕ∞} [IsManifold I n M] (hmn : m ≤ n) : IsManifold I m M := by
  exact IsManifold.of_le hmn

theorem smooth_manifold_is_topological {𝕜 : Type u} [NontriviallyNormedField 𝕜]
    {E : Type v} [NormedAddCommGroup E] [NormedSpace 𝕜 E]
    {H : Type w} [TopologicalSpace H] {I : ModelWithCorners 𝕜 E H}
    {M : Type u'} [TopologicalSpace M] [ChartedSpace H M]
    [IsManifold I ∞ M] : IsManifold I 0 M := by
  infer_instance

theorem product_of_manifolds {𝕜 : Type u} [NontriviallyNormedField 𝕜]
    {E : Type v} [NormedAddCommGroup E] [NormedSpace 𝕜 E]
    {E' : Type v'} [NormedAddCommGroup E'] [NormedSpace 𝕜 E']
    {H : Type w} [TopologicalSpace H] {H' : Type*} [TopologicalSpace H']
    {I : ModelWithCorners 𝕜 E H} {I' : ModelWithCorners 𝕜 E' H'}
    {M : Type u'} [TopologicalSpace M] [ChartedSpace H M]
    {M' : Type*} [TopologicalSpace M'] [ChartedSpace H' M']
    (n : WithTop ℕ∞) [IsManifold I n M] [IsManifold I' n M'] :
    IsManifold (I.prod I') n (M × M') := by
  exact IsManifold.prod M M'

noncomputable def tangent_zero {𝕜 : Type u} [NontriviallyNormedField 𝕜]
    {E : Type v} [NormedAddCommGroup E] [NormedSpace 𝕜 E]
    {H : Type w} [TopologicalSpace H] (I : ModelWithCorners 𝕜 E H)
    {M : Type u'} [TopologicalSpace M] [ChartedSpace H M] (x : M) : TangentSpace I x := by
  exact 0

def tangent_vector_as_bundle_point {𝕜 : Type u} [NontriviallyNormedField 𝕜]
    {E : Type v} [NormedAddCommGroup E] [NormedSpace 𝕜 E]
    {H : Type w} [TopologicalSpace H] (I : ModelWithCorners 𝕜 E H)
    {M : Type u'} [TopologicalSpace M] [ChartedSpace H M]
    {x : M} (v : TangentSpace I x) : TangentBundle I M := by
  exact ⟨x, v⟩

theorem tangent_bundle_base {𝕜 : Type u} [NontriviallyNormedField 𝕜]
    {E : Type v} [NormedAddCommGroup E] [NormedSpace 𝕜 E]
    {H : Type w} [TopologicalSpace H] (I : ModelWithCorners 𝕜 E H)
    {M : Type u'} [TopologicalSpace M] [ChartedSpace H M]
    {x : M} (v : TangentSpace I x) : (⟨x, v⟩ : TangentBundle I M).1 = x := by
  rfl

theorem tangent_bundle_has_zero {𝕜 : Type u} [NontriviallyNormedField 𝕜]
    {E : Type v} [NormedAddCommGroup E] [NormedSpace 𝕜 E]
    {H : Type w} [TopologicalSpace H] (I : ModelWithCorners 𝕜 E H)
    {M : Type u'} [TopologicalSpace M] [ChartedSpace H M] (x : M) :
    ∃ p : TangentBundle I M, p.1 = x := by
  refine ⟨⟨x, tangent_zero I x⟩, ?_⟩
  rfl

end ManifoldAdventure
