module

public import ManifoldAdventure.Homeomorphisms
public import ManifoldAdventure.LocalCharts
public import ManifoldAdventure.ChartedSpaces
public import ManifoldAdventure.CanonicalCharts
public import ManifoldAdventure.SmoothManifolds
public import ManifoldAdventure.TangentSpaces
public import ManifoldAdventure.MapProjections
public import ManifoldAdventure.CircleMotion
public import ManifoldAdventure.RobotArm

@[expose] public section

/-!
# Manifold Adventure: complete browser theorem base

Generated by `scripts/create-manifold-game.mjs`. Browser verification imports
the narrower world modules above; this umbrella is retained for full-course
validation and review.
-/
