module

public import Mathlib.Geometry.Manifold.ChartedSpace

@[expose] public section

/-!
# Manifold Adventure: Identity and product charts

Generated by `scripts/create-manifold-game.mjs`.

Exercise declarations live in `ManifoldAdventure`; the mathematical
structures and library theorems they use come directly from pinned Mathlib.
-/

namespace ManifoldAdventure

universe u v w u' v'

open scoped Topology
open Filter

theorem self_chart_is_identity {Coordinates : Type u}
    [coordinateTopology : TopologicalSpace Coordinates]
    (mark : Coordinates) :
    chartAt Coordinates mark = OpenPartialHomeomorph.refl Coordinates := by
  exact chartAt_self_eq

theorem self_atlas_only_identity {Coordinates : Type u}
    [coordinateTopology : TopologicalSpace Coordinates]
    (chart : OpenPartialHomeomorph Coordinates Coordinates) :
    chart ∈ atlas Coordinates Coordinates ↔
      chart = OpenPartialHomeomorph.refl Coordinates := by
  constructor
  · intro h
    exact chartedSpaceSelf_atlas.mp h
  · intro h
    exact chartedSpaceSelf_atlas.mpr h

theorem product_chart_is_product {FirstCoordinates : Type u} {SecondCoordinates : Type u'}
    {FirstSurface : Type v} {SecondSurface : Type v'}
    [firstCoordinateTopology : TopologicalSpace FirstCoordinates]
    [secondCoordinateTopology : TopologicalSpace SecondCoordinates]
    [firstSurfaceTopology : TopologicalSpace FirstSurface]
    [secondSurfaceTopology : TopologicalSpace SecondSurface]
    [firstSurfaceCharts : ChartedSpace FirstCoordinates FirstSurface]
    [secondSurfaceCharts : ChartedSpace SecondCoordinates SecondSurface]
    (position : FirstSurface × SecondSurface) :
    chartAt (ModelProd FirstCoordinates SecondCoordinates) position =
      (chartAt FirstCoordinates position.1).prod
        (chartAt SecondCoordinates position.2) := by
  rw [prodChartedSpace_chartAt]

theorem product_point_mem_chart_source {FirstCoordinates : Type u} {SecondCoordinates : Type u'}
    {FirstSurface : Type v} {SecondSurface : Type v'}
    [firstCoordinateTopology : TopologicalSpace FirstCoordinates]
    [secondCoordinateTopology : TopologicalSpace SecondCoordinates]
    [firstSurfaceTopology : TopologicalSpace FirstSurface]
    [secondSurfaceTopology : TopologicalSpace SecondSurface]
    [firstSurfaceCharts : ChartedSpace FirstCoordinates FirstSurface]
    [secondSurfaceCharts : ChartedSpace SecondCoordinates SecondSurface]
    (firstPosition : FirstSurface) (secondPosition : SecondSurface) :
    (firstPosition, secondPosition) ∈
      (chartAt (ModelProd FirstCoordinates SecondCoordinates)
        (firstPosition, secondPosition)).source := by
  simpa only using
    (mem_chart_source (ModelProd FirstCoordinates SecondCoordinates)
      (firstPosition, secondPosition))

end ManifoldAdventure
