module

public import Mathlib.Geometry.Manifold.Instances.Sphere
public import Mathlib.Analysis.SpecialFunctions.Complex.Circle
public import ManifoldAdventure.BrowserPolicy
public import ManifoldAdventure.SmoothManifolds

@[expose] public section

/-!
# Manifold Adventure: The dial comes around

Generated by `scripts/create-manifold-game.mjs`.

Exercise declarations live in `ManifoldAdventure`; the mathematical
structures and library theorems they use come directly from pinned Mathlib.
-/

namespace ManifoldAdventure

universe u v w u' v' w' u''

open scoped Topology Manifold ContDiff
open Function

theorem circle_zero_turn : Circle.exp 0 = 1 := by
  exact Circle.exp_zero

theorem circle_turns_compose (first second : ℝ) :
    Circle.exp (first + second) = Circle.exp first * Circle.exp second := by
  exact Circle.exp_add first second

theorem circle_full_turn (angle : ℝ) :
    Circle.exp (angle + 2 * Real.pi) = Circle.exp angle := by
  exact Circle.exp_add_two_pi angle

theorem circle_turning_is_smooth : CMDiff ∞ Circle.exp := by
  exact contMDiff_circleExp

end ManifoldAdventure
