module

public import ManifoldAdventure.BrowserPolicy
public import ManifoldAdventure.TangentSpaces
public import ManifoldAdventure.MapProjections
public import ManifoldAdventure.RobotReachability

@[expose] public section

/-!
# Manifold Adventure: Sphere, transition maps, and tangent vectors

Generated by `scripts/create-manifold-game.mjs`.

Exercise declarations live in `ManifoldAdventure`; the mathematical
structures and library theorems they use come directly from pinned Mathlib.
-/

namespace ManifoldAdventure

universe u v w u' v' w' u''

open scoped Topology Manifold ContDiff
open Metric Set Function

theorem two_leaves_cover_point {Space : Type u} [NormedAddCommGroup Space]
    [InnerProductSpace ℝ Space]
    (north south : sphere (0 : Space) 1) (different : north ≠ south)
    (place : sphere (0 : Space) 1) :
    place ∈ (stereographic (norm_eq_of_mem_sphere north)).source ∨
      place ∈ (stereographic (norm_eq_of_mem_sphere south)).source := by
  simp only [stereographic_source, Set.mem_compl_iff, Set.mem_singleton_iff]
  by_cases atNorth : place = north
  · right
    intro atSouth
    exact different (atNorth.symm.trans atSouth)
  · left
    exact atNorth

theorem sphere_preferred_chart {Space : Type u} [NormedAddCommGroup Space]
    [InnerProductSpace ℝ Space] {dimension : ℕ}
    [Fact (Module.finrank ℝ Space = dimension + 1)]
    (place : sphere (0 : Space) 1) :
    chartAt (EuclideanSpace ℝ (Fin dimension)) place = stereographic' dimension (-place) := by
  rfl

theorem sphere_chart_in_atlas {Space : Type u} [NormedAddCommGroup Space]
    [InnerProductSpace ℝ Space] {dimension : ℕ}
    [Fact (Module.finrank ℝ Space = dimension + 1)]
    (pole : sphere (0 : Space) 1) :
    stereographic' dimension pole ∈ atlas (EuclideanSpace ℝ (Fin dimension)) (sphere (0 : Space) 1) := by
  exact ⟨pole, rfl⟩

theorem chart_change_is_smooth {Scalar : Type u} [NontriviallyNormedField Scalar]
    {Vectors : Type v} [NormedAddCommGroup Vectors]
    [NormedSpace Scalar Vectors]
    {Coordinates : Type w} [TopologicalSpace Coordinates]
    {model : ModelWithCorners Scalar Vectors Coordinates}
    {Surface : Type u'} [TopologicalSpace Surface]
    [ChartedSpace Coordinates Surface]
    {order : WithTop ℕ∞} [IsManifold model order Surface]
    (chart chart' : OpenPartialHomeomorph Surface Coordinates)
    (inAtlas : chart ∈ atlas Coordinates Surface)
    (inAtlas' : chart' ∈ atlas Coordinates Surface) :
    chart.symm ≫ₕ chart' ∈ contDiffGroupoid order model := by
  exact HasGroupoid.compatible inAtlas inAtlas'

theorem chart_change_contDiffOn {Scalar : Type u} [NontriviallyNormedField Scalar]
    {Vectors : Type v} [NormedAddCommGroup Vectors]
    [NormedSpace Scalar Vectors]
    {Coordinates : Type w} [TopologicalSpace Coordinates]
    {model : ModelWithCorners Scalar Vectors Coordinates}
    {Surface : Type u'} [TopologicalSpace Surface]
    [ChartedSpace Coordinates Surface]
    {order : WithTop ℕ∞} [IsManifold model order Surface]
    (chart chart' : OpenPartialHomeomorph Surface Coordinates)
    (inAtlas : chart ∈ atlas Coordinates Surface)
    (inAtlas' : chart' ∈ atlas Coordinates Surface) :
    ContDiffOn Scalar order (model ∘ (chart.symm ≫ₕ chart') ∘ model.symm)
      (model.symm ⁻¹' (chart.symm ≫ₕ chart').source ∩ Set.range model) := by
  have compatible := HasGroupoid.compatible (G := contDiffGroupoid order model) inAtlas inAtlas'
  exact (mem_groupoid_of_pregroupoid.mp compatible).1

theorem sphere_chart_change_smooth {Space : Type u} [NormedAddCommGroup Space]
    [InnerProductSpace ℝ Space] {dimension : ℕ}
    [Fact (Module.finrank ℝ Space = dimension + 1)]
    (pole pole' : sphere (0 : Space) 1) :
    (stereographic' dimension pole).symm ≫ₕ stereographic' dimension pole' ∈
      contDiffGroupoid ∞ (𝓡 dimension) := by
  exact HasGroupoid.compatible (sphere_chart_in_atlas pole) (sphere_chart_in_atlas pole')

theorem sphere_inclusion_smooth {Space : Type u} [NormedAddCommGroup Space]
    [InnerProductSpace ℝ Space] {dimension : ℕ}
    [Fact (Module.finrank ℝ Space = dimension + 1)] :
    ContMDiff (𝓡 dimension) 𝓘(ℝ, Space) ∞ ((↑) : sphere (0 : Space) 1 → Space) := by
  exact contMDiff_coe_sphere

theorem tangent_vectors_are_vectors {Space : Type u} [NormedAddCommGroup Space]
    [InnerProductSpace ℝ Space] {dimension : ℕ}
    [Fact (Module.finrank ℝ Space = dimension + 1)]
    (place : sphere (0 : Space) 1) :
    Function.Injective
      (mfderiv (𝓡 dimension) 𝓘(ℝ, Space) ((↑) : sphere (0 : Space) 1 → Space) place) := by
  exact mfderiv_coe_sphere_injective place

theorem tangent_plane_is_orthogonal {Space : Type u} [NormedAddCommGroup Space]
    [InnerProductSpace ℝ Space] {dimension : ℕ}
    [Fact (Module.finrank ℝ Space = dimension + 1)]
    (place : sphere (0 : Space) 1) :
    LinearMap.range (ContinuousLinearMap.toLinearMap
      (mfderiv (𝓡 dimension) 𝓘(ℝ, Space) ((↑) : sphere (0 : Space) 1 → Space) place))
      = (ℝ ∙ (place : Space))ᗮ := by
  exact range_mfderiv_coe_sphere place

theorem same_point_iff_full_turns (first second : ℝ) :
    Circle.exp first = Circle.exp second ↔
      ∃ turns : ℤ, first = second + turns * (2 * Real.pi) := by
  exact Circle.exp_eq_exp

end ManifoldAdventure
