module

public import Mathlib.Topology.OpenPartialHomeomorph.Defs
public import ManifoldAdventure.BrowserPolicy
public import ManifoldAdventure.Homeomorphisms

@[expose] public section

/-!
# Manifold Adventure: Open partial homeomorphisms

Generated by `scripts/create-manifold-game.mjs`.

Exercise declarations live in `ManifoldAdventure`; the mathematical
structures and library theorems they use come directly from pinned Mathlib.
-/

namespace ManifoldAdventure

universe u v w u' v' w' u''

open scoped Topology
open Filter

theorem local_chart_source_open {Stone : Type u} {Drawing : Type v}
    [TopologicalSpace Stone] [TopologicalSpace Drawing]
    (chart : OpenPartialHomeomorph Stone Drawing) : IsOpen chart.source := by
  exact chart.open_source

theorem local_chart_continuous {Stone : Type u} {Drawing : Type v}
    [TopologicalSpace Stone] [TopologicalSpace Drawing]
    (chart : OpenPartialHomeomorph Stone Drawing) :
    ContinuousOn chart chart.source := by
  exact chart.continuousOn

theorem local_chart_maps_source {Stone : Type u} {Drawing : Type v}
    [TopologicalSpace Stone] [TopologicalSpace Drawing]
    (chart : OpenPartialHomeomorph Stone Drawing)
    (place : Stone) (inPatch : place ∈ chart.source) :
    chart place ∈ chart.target := by
  apply chart.map_source
  exact inPatch

theorem local_chart_round_trip {Stone : Type u} {Drawing : Type v}
    [TopologicalSpace Stone] [TopologicalSpace Drawing]
    (chart : OpenPartialHomeomorph Stone Drawing)
    (place : Stone) (inPatch : place ∈ chart.source) :
    chart.symm (chart place) = place := by
  exact chart.left_inv inPatch

theorem local_chart_reads_back {Stone : Type u} {Drawing : Type v}
    [TopologicalSpace Stone] [TopologicalSpace Drawing]
    (chart : OpenPartialHomeomorph Stone Drawing)
    (mark : Drawing) (inDrawing : mark ∈ chart.target) :
    chart.symm mark ∈ chart.source ∧ chart (chart.symm mark) = mark := by
  constructor
  · exact chart.map_target inDrawing
  · exact chart.right_inv inDrawing

end ManifoldAdventure
