module

public import Mathlib.Geometry.Manifold.Instances.Sphere
public import ManifoldAdventure.BrowserPolicy
public import ManifoldAdventure.LocalCharts

@[expose] public section

/-!
# Manifold Adventure: One pole is missing

Generated by `scripts/create-manifold-game.mjs`.

Exercise declarations live in `ManifoldAdventure`; the mathematical
structures and library theorems they use come directly from pinned Mathlib.
-/

namespace ManifoldAdventure

universe u v w u' v' w' u''

open scoped Topology Manifold ContDiff
open Metric Set Function

theorem stereographic_map_misses_pole {Space : Type u} [NormedAddCommGroup Space]
    [InnerProductSpace ℝ Space]
    (pole : Space) (unitPole : ‖pole‖ = 1) :
    (stereographic unitPole).source = {⟨pole, by simp [unitPole]⟩}ᶜ := by
  exact stereographic_source unitPole

theorem opposite_pole_is_origin {Space : Type u} [NormedAddCommGroup Space]
    [InnerProductSpace ℝ Space]
    (pole : sphere (0 : Space) 1) :
    stereographic (norm_eq_of_mem_sphere pole) (-pole) = 0 := by
  exact stereographic_apply_neg pole

theorem every_stereographic_mark_has_source {Space : Type u} [NormedAddCommGroup Space]
    [InnerProductSpace ℝ Space]
    (pole : Space) (unitPole : ‖pole‖ = 1) :
    Function.Surjective (stereographic unitPole) := by
  exact surjective_stereographic unitPole

theorem stereographic_off_pole {Space : Type u} [NormedAddCommGroup Space]
    [InnerProductSpace ℝ Space]
    (north place : sphere (0 : Space) 1) (notNorth : place ≠ north) :
    place ∈ (stereographic (norm_eq_of_mem_sphere north)).source := by
  simp only [stereographic_source, Set.mem_compl_iff, Set.mem_singleton_iff]
  exact notNorth

theorem two_stereographic_maps_cover {Space : Type u} [NormedAddCommGroup Space]
    [InnerProductSpace ℝ Space]
    (north south : sphere (0 : Space) 1) (different : north ≠ south) :
    (stereographic (norm_eq_of_mem_sphere north)).source ∪
      (stereographic (norm_eq_of_mem_sphere south)).source = Set.univ := by
  ext place
  simp only [stereographic_source, Set.mem_union, Set.mem_compl_iff,
    Set.mem_singleton_iff, Set.mem_univ, iff_true]
  by_cases atNorth : place = north
  · right
    intro atSouth
    exact different (atNorth.symm.trans atSouth)
  · left
    exact atNorth

end ManifoldAdventure
