module

public import ManifoldAdventure.BrowserPolicy
public import ManifoldAdventure.RobotArm

@[expose] public section

/-!
# Manifold Adventure: Can the arm touch it?

Generated by `scripts/create-manifold-game.mjs`.

Exercise declarations live in `ManifoldAdventure`; the mathematical
structures and library theorems they use come directly from pinned Mathlib.
-/

namespace ManifoldAdventure

universe u v w u' v' w' u''

open scoped Topology Manifold ContDiff
open Function

theorem robot_tip_norm_le (firstLength secondLength : ℝ)
    (hFirst : 0 ≤ firstLength) (hSecond : 0 ≤ secondLength)
    (joints : Circle × Circle) :
    ‖robot_arm_tip firstLength secondLength joints‖ ≤
      firstLength + secondLength := by
  unfold robot_arm_tip
  calc
    _ ≤ ‖(firstLength : ℂ) * (joints.1 : ℂ)‖ +
        ‖(secondLength : ℂ) * ((joints.1 * joints.2 : Circle) : ℂ)‖ := norm_add_le _ _
    _ = firstLength + secondLength := by
      simp [Circle.norm_coe, abs_of_nonneg, hFirst, hSecond]

theorem robot_tip_norm_ge (firstLength secondLength : ℝ)
    (hFirst : 0 ≤ firstLength) (hSecond : 0 ≤ secondLength)
    (joints : Circle × Circle) :
    |firstLength - secondLength| ≤
      ‖robot_arm_tip firstLength secondLength joints‖ := by
  unfold robot_arm_tip
  apply abs_sub_le_iff.mpr
  constructor
  · have h := norm_sub_norm_le
      ((firstLength : ℂ) * (joints.1 : ℂ))
      (-((secondLength : ℂ) * ((joints.1 * joints.2 : Circle) : ℂ)))
    simpa [Circle.norm_coe, abs_of_nonneg, hFirst, hSecond] using h
  · have h := norm_sub_norm_le
      ((secondLength : ℂ) * ((joints.1 * joints.2 : Circle) : ℂ))
      (-((firstLength : ℂ) * (joints.1 : ℂ)))
    simpa [Circle.norm_coe, abs_of_nonneg, hFirst, hSecond, add_comm] using h

theorem robot_tip_mem_reach_annulus (firstLength secondLength : ℝ)
    (hFirst : 0 ≤ firstLength) (hSecond : 0 ≤ secondLength)
    (joints : Circle × Circle) :
    |firstLength - secondLength| ≤
        ‖robot_arm_tip firstLength secondLength joints‖ ∧
      ‖robot_arm_tip firstLength secondLength joints‖ ≤
        firstLength + secondLength := by
  constructor
  · exact robot_tip_norm_ge firstLength secondLength hFirst hSecond joints
  · exact robot_tip_norm_le firstLength secondLength hFirst hSecond joints

theorem robot_target_outside_annulus_unreachable (firstLength secondLength : ℝ)
    (hFirst : 0 ≤ firstLength) (hSecond : 0 ≤ secondLength)
    (point : ℂ)
    (outside : ‖point‖ < |firstLength - secondLength| ∨
      firstLength + secondLength < ‖point‖) :
    ¬ ∃ joints : Circle × Circle,
      robot_arm_tip firstLength secondLength joints = point := by
  intro reaches
  obtain ⟨joints, rfl⟩ := reaches
  rcases outside with tooClose | tooFar
  · exact (not_lt_of_ge
      (robot_tip_norm_ge firstLength secondLength hFirst hSecond joints)) tooClose
  · exact (not_lt_of_ge
      (robot_tip_norm_le firstLength secondLength hFirst hSecond joints)) tooFar

end ManifoldAdventure
