module

public import ManifoldAdventure.BrowserPolicy
public import ManifoldAdventure.CircleMotion

@[expose] public section

/-!
# Manifold Adventure: Two hinges, one reach

Generated by `scripts/create-manifold-game.mjs`.

Exercise declarations live in `ManifoldAdventure`; the mathematical
structures and library theorems they use come directly from pinned Mathlib.
-/

namespace ManifoldAdventure

universe u v w u' v' w' u''

open scoped Topology Manifold ContDiff
open Function

noncomputable def robot_arm_tip (firstLength secondLength : ℝ)
    (joints : Circle × Circle) : ℂ := by
  exact
    (firstLength : ℂ) * (joints.1 : ℂ) +
      (secondLength : ℂ) * ((joints.1 * joints.2 : Circle) : ℂ)

theorem robot_arm_at_rest (firstLength secondLength : ℝ) :
    robot_arm_tip firstLength secondLength (1, 1) =
      (firstLength + secondLength : ℝ) := by
  simp [robot_arm_tip]

theorem robot_full_turn_same_tip (firstLength secondLength shoulder elbow : ℝ) :
    robot_arm_tip firstLength secondLength
        (Circle.exp (shoulder + 2 * Real.pi), Circle.exp elbow) =
      robot_arm_tip firstLength secondLength
        (Circle.exp shoulder, Circle.exp elbow) := by
  rw [Circle.exp_add_two_pi]

theorem robot_arm_tip_continuous (firstLength secondLength : ℝ) :
    Continuous (robot_arm_tip firstLength secondLength) := by
  unfold robot_arm_tip
  exact (continuous_const.mul (continuous_subtype_val.comp continuous_fst)).add
    (continuous_const.mul ((continuous_subtype_val.comp continuous_fst).mul
      (continuous_subtype_val.comp continuous_snd)))

end ManifoldAdventure
