module

public import Mathlib.Geometry.Manifold.IsManifold.Basic
public import ManifoldAdventure.BrowserPolicy
public import ManifoldAdventure.CanonicalCharts

@[expose] public section

/-!
# Manifold Adventure: Smooth manifolds

Generated by `scripts/create-manifold-game.mjs`.

Exercise declarations live in `ManifoldAdventure`; the mathematical
structures and library theorems they use come directly from pinned Mathlib.
-/

namespace ManifoldAdventure

universe u v w u' v' w' u''

open scoped Topology ContDiff
open Filter ENat

theorem transition_map_source {Stone : Type u} {Drawing : Type v}
    [TopologicalSpace Stone] [TopologicalSpace Drawing]
    (chart chart' : OpenPartialHomeomorph Stone Drawing) :
    (chart.symm.trans chart').source =
      chart.target ∩ chart.symm ⁻¹' chart'.source := by
  rw [OpenPartialHomeomorph.trans_source, OpenPartialHomeomorph.symm_source]

theorem model_space_is_manifold {Scalar : Type u}
    [NontriviallyNormedField Scalar]
    {Vectors : Type v} [NormedAddCommGroup Vectors]
    [NormedSpace Scalar Vectors]
    {Coordinates : Type w}
    [TopologicalSpace Coordinates]
    (model : ModelWithCorners Scalar Vectors Coordinates)
    (order : WithTop ℕ∞) :
    IsManifold model order Coordinates := by
  infer_instance

theorem manifold_of_higher_smoothness {Scalar : Type u}
    [NontriviallyNormedField Scalar]
    {Vectors : Type v} [NormedAddCommGroup Vectors]
    [NormedSpace Scalar Vectors]
    {Coordinates : Type w}
    [TopologicalSpace Coordinates]
    {model : ModelWithCorners Scalar Vectors Coordinates}
    {Surface : Type u'} [TopologicalSpace Surface]
    [ChartedSpace Coordinates Surface]
    {lowerOrder higherOrder : WithTop ℕ∞}
    [IsManifold model higherOrder Surface] :
    lowerOrder ≤ higherOrder → IsManifold model lowerOrder Surface := by
  intro order_le
  exact IsManifold.of_le order_le

theorem smooth_manifold_is_topological {Scalar : Type u}
    [NontriviallyNormedField Scalar]
    {Vectors : Type v} [NormedAddCommGroup Vectors]
    [NormedSpace Scalar Vectors]
    {Coordinates : Type w}
    [TopologicalSpace Coordinates]
    {model : ModelWithCorners Scalar Vectors Coordinates}
    {Surface : Type u'} [TopologicalSpace Surface]
    [ChartedSpace Coordinates Surface]
    [IsManifold model ∞ Surface] :
    IsManifold model 0 Surface := by
  infer_instance

theorem product_of_manifolds {Scalar : Type u}
    [NontriviallyNormedField Scalar]
    {FirstVectors : Type v}
    [NormedAddCommGroup FirstVectors]
    [NormedSpace Scalar FirstVectors]
    {SecondVectors : Type v'}
    [NormedAddCommGroup SecondVectors]
    [NormedSpace Scalar SecondVectors]
    {FirstCoordinates : Type w}
    [TopologicalSpace FirstCoordinates]
    {SecondCoordinates : Type w'}
    [TopologicalSpace SecondCoordinates]
    {firstModel : ModelWithCorners Scalar FirstVectors FirstCoordinates}
    {secondModel : ModelWithCorners Scalar SecondVectors SecondCoordinates}
    {FirstSurface : Type u'}
    [TopologicalSpace FirstSurface]
    [ChartedSpace FirstCoordinates FirstSurface]
    {SecondSurface : Type u''}
    [TopologicalSpace SecondSurface]
    [ChartedSpace SecondCoordinates SecondSurface]
    (order : WithTop ℕ∞)
    [IsManifold firstModel order FirstSurface]
    [IsManifold secondModel order SecondSurface] :
    IsManifold (firstModel.prod secondModel) order (FirstSurface × SecondSurface) := by
  exact IsManifold.prod FirstSurface SecondSurface

end ManifoldAdventure
