module

public import Mathlib.Geometry.Manifold.IsManifold.Basic

@[expose] public section

/-!
# Manifold Adventure: Smooth manifolds

Generated by `scripts/create-manifold-game.mjs`.

Exercise declarations live in `ManifoldAdventure`; the mathematical
structures and library theorems they use come directly from pinned Mathlib.
-/

namespace ManifoldAdventure

universe u v w u' v'

open scoped Topology ContDiff
open Filter ENat

theorem model_space_is_manifold {Scalar : Type u}
    [scalarField : NontriviallyNormedField Scalar]
    {Vectors : Type v} [vectorGroup : NormedAddCommGroup Vectors]
    [vectorSpace : NormedSpace Scalar Vectors]
    {Coordinates : Type w}
    [coordinateTopology : TopologicalSpace Coordinates]
    (model : ModelWithCorners Scalar Vectors Coordinates)
    (order : WithTop ℕ∞) :
    IsManifold model order Coordinates := by
  infer_instance

theorem manifold_of_higher_smoothness {Scalar : Type u}
    [scalarField : NontriviallyNormedField Scalar]
    {Vectors : Type v} [vectorGroup : NormedAddCommGroup Vectors]
    [vectorSpace : NormedSpace Scalar Vectors]
    {Coordinates : Type w}
    [coordinateTopology : TopologicalSpace Coordinates]
    {model : ModelWithCorners Scalar Vectors Coordinates}
    {Surface : Type u'} [surfaceTopology : TopologicalSpace Surface]
    [surfaceCharts : ChartedSpace Coordinates Surface]
    {lowerOrder higherOrder : WithTop ℕ∞}
    [higherSmoothness : IsManifold model higherOrder Surface]
    (order_le : lowerOrder ≤ higherOrder) :
    IsManifold model lowerOrder Surface := by
  exact IsManifold.of_le order_le

theorem smooth_manifold_is_topological {Scalar : Type u}
    [scalarField : NontriviallyNormedField Scalar]
    {Vectors : Type v} [vectorGroup : NormedAddCommGroup Vectors]
    [vectorSpace : NormedSpace Scalar Vectors]
    {Coordinates : Type w}
    [coordinateTopology : TopologicalSpace Coordinates]
    {model : ModelWithCorners Scalar Vectors Coordinates}
    {Surface : Type u'} [surfaceTopology : TopologicalSpace Surface]
    [surfaceCharts : ChartedSpace Coordinates Surface]
    [smoothSurface : IsManifold model ∞ Surface] :
    IsManifold model 0 Surface := by
  infer_instance

theorem product_of_manifolds {Scalar : Type u}
    [scalarField : NontriviallyNormedField Scalar]
    {FirstVectors : Type v}
    [firstVectorGroup : NormedAddCommGroup FirstVectors]
    [firstVectorSpace : NormedSpace Scalar FirstVectors]
    {SecondVectors : Type v'}
    [secondVectorGroup : NormedAddCommGroup SecondVectors]
    [secondVectorSpace : NormedSpace Scalar SecondVectors]
    {FirstCoordinates : Type w}
    [firstCoordinateTopology : TopologicalSpace FirstCoordinates]
    {SecondCoordinates : Type*}
    [secondCoordinateTopology : TopologicalSpace SecondCoordinates]
    {firstModel : ModelWithCorners Scalar FirstVectors FirstCoordinates}
    {secondModel : ModelWithCorners Scalar SecondVectors SecondCoordinates}
    {FirstSurface : Type u'}
    [firstSurfaceTopology : TopologicalSpace FirstSurface]
    [firstSurfaceCharts : ChartedSpace FirstCoordinates FirstSurface]
    {SecondSurface : Type*}
    [secondSurfaceTopology : TopologicalSpace SecondSurface]
    [secondSurfaceCharts : ChartedSpace SecondCoordinates SecondSurface]
    (order : WithTop ℕ∞)
    [firstSmoothness : IsManifold firstModel order FirstSurface]
    [secondSmoothness : IsManifold secondModel order SecondSurface] :
    IsManifold (firstModel.prod secondModel) order (FirstSurface × SecondSurface) := by
  exact IsManifold.prod FirstSurface SecondSurface

end ManifoldAdventure
