module

public import Mathlib.Geometry.Manifold.IsManifold.Basic
public import ManifoldAdventure.BrowserPolicy
public import ManifoldAdventure.SmoothManifolds

@[expose] public section

/-!
# Manifold Adventure: Tangent spaces and the tangent bundle

Generated by `scripts/create-manifold-game.mjs`.

Exercise declarations live in `ManifoldAdventure`; the mathematical
structures and library theorems they use come directly from pinned Mathlib.
-/

namespace ManifoldAdventure

universe u v w u' v' w' u''

open scoped Topology ContDiff
open Filter ENat

noncomputable def tangent_zero {Scalar : Type u}
    [NontriviallyNormedField Scalar]
    {Vectors : Type v} [NormedAddCommGroup Vectors]
    [NormedSpace Scalar Vectors]
    {Coordinates : Type w}
    [TopologicalSpace Coordinates]
    (model : ModelWithCorners Scalar Vectors Coordinates)
    {Surface : Type u'} [TopologicalSpace Surface]
    [ChartedSpace Coordinates Surface] (place : Surface) :
    TangentSpace model place := by
  exact 0

theorem tangent_bundle_base {Scalar : Type u}
    [NontriviallyNormedField Scalar]
    {Vectors : Type v} [NormedAddCommGroup Vectors]
    [NormedSpace Scalar Vectors]
    {Coordinates : Type w}
    [TopologicalSpace Coordinates]
    (model : ModelWithCorners Scalar Vectors Coordinates)
    {Surface : Type u'} [TopologicalSpace Surface]
    [ChartedSpace Coordinates Surface]
    {place : Surface} (velocity : TangentSpace model place) :
    (⟨place, velocity⟩ : TangentBundle model Surface).1 = place := by
  rfl

theorem tangent_bundle_has_zero {Scalar : Type u}
    [NontriviallyNormedField Scalar]
    {Vectors : Type v} [NormedAddCommGroup Vectors]
    [NormedSpace Scalar Vectors]
    {Coordinates : Type w}
    [TopologicalSpace Coordinates]
    (model : ModelWithCorners Scalar Vectors Coordinates)
    {Surface : Type u'} [TopologicalSpace Surface]
    [ChartedSpace Coordinates Surface] (place : Surface) :
    ∃ bundlePoint : TangentBundle model Surface, bundlePoint.1 = place := by
  refine ⟨⟨place, tangent_zero model place⟩, ?_⟩
  rfl

end ManifoldAdventure
